FROM ghcr.io/cirruslabs/flutter:stable AS base

WORKDIR /app

COPY mobile/pubspec.* ./

RUN flutter pub get

COPY mobile/ .

# Development Stage
FROM base AS dev
EXPOSE 8080
CMD ["flutter", "run", "-d", "web-server", "--web-port", "8080", "--web-hostname", "0.0.0.0"]

# Builder Stage for Production
FROM base AS builder
RUN flutter build web --release

# Production Stage
FROM nginx:alpine AS prod
COPY --from=builder /app/build/web /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]