FROM node:22-bookworm-slim

WORKDIR /app

RUN apt-get update && apt-get install -y libssl3 ca-certificates && rm -rf /var/lib/apt/lists/*

COPY api/package*.json ./

RUN npm ci

COPY api/ ./

RUN npx prisma generate

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]