# Task types
TASK_TYPE_POST = 'POST'
TASK_TYPE_DOCUMENT = 'DOCUMENT'
TASK_TYPE_KNOWLEDGE_BASE = 'KNOWLEDGE_BASE'

# Embedding statuses
STATUS_PENDING = 'PENDING'
STATUS_PROCESSING = 'PROCESSING'
STATUS_COMPLETED = 'COMPLETED'
STATUS_FAILED = 'FAILED'

# Content types
CONTENT_TYPE_TEXT = 'text'
CONTENT_TYPE_TABLE = 'table'
CONTENT_TYPE_IMAGE = 'image'
